### ISSUE TITLE
Method for measuring time on the host

### ISSUE THREAD

**Issue by jnider** [UBC-ECE-Sasha/PIM-common#3]
There are many  API functions available in Linux for measuring time. Currently, we are using gettimeofday() which returns elapsed time since the epoch with microsecond accuracy. There are some corner cases under which this will have weird behaviour, but is generally stable. This function has been marked obsolete under POSIX, but is still maintained in modern Linux.

Another alternative is clock_gettime(), which POSIX-2008 suggests as a replacement for gettimeofday(). It has nanosecond accuracy, although that is implementation dependent. We should investigate using clock_gettime with CLOCK_MONOTONIC or CLOCK_MONOTONIC_RAW. This also has some weird corner cases (i.e. under process migration) but those will probably not affect us.

**Comment by craiig** [comment]
My pref is `clock_gettime(CLOCK_MONOTONIC, &start);` but the nanosecond resolution is often a bit overkill but usually harmless.

Here's a helper function that converts timespec structs to nanoseconds:

```
double duration_nsec(struct timespec *t1, struct timespec *t0){
  double nsec;
  if(t1->tv_nsec < t0->tv_nsec){
    // Borrow from second and add to nsec
    nsec = (t1->tv_sec - 1 - (t0->tv_sec)) * 1e9 + t1->tv_nsec + 1e9 - t0->tv_nsec;
  }

  else{
    nsec = (t1->tv_sec - (t0->tv_sec)) * 1e9 + t1->tv_nsec - t0->tv_nsec;
  }

  return nsec;
}
```

Here's a quick test that compares gettime to rdtsc that I used to convince myself that gettime was decent. 
```
__inline__ uint64_t rdtsc(void) {
  uint32_t lo, hi;
  /* see: https://github.com/google/benchmark/blob/master/src/cycleclock.h */
  /*
  __asm__ __volatile__ (      // serialize
  "xorl %%eax,%%eax \n        cpuid"
  ::: "%rax", "%rbx", "%rcx", "%rdx");
  __asm__ __volatile__ ("rdtsc" : "=a" (lo), "=d" (hi));
  */
  __asm__ volatile("rdtsc" : "=a"(lo), "=d"(hi));
  return (uint64_t)hi << 32 | lo;
}
static double GetNominalCPUFrequency() {
  unsigned freq;
  size_t size = sizeof(freq);
  int mib[2] = {CTL_HW, HW_CPU_FREQ};
  if (sysctl(mib, 2, &freq, &size, NULL, 0) == 0) {
    return (double)(freq);
  }
  return 1.0;
}

int main(int argc, char *argv[]){
  struct timespec t0, t1, t2;
  t0.tv_sec = 0;
  t0.tv_nsec = 0;
  t1 = t0;
  t2 = t0;

  clock_gettime(CLOCK_MONOTONIC, &t0);
  sleep(1);
  clock_gettime(CLOCK_MONOTONIC, &t1);
  uint64_t start = rdtsc();
  sleep(1);
  uint64_t stop = rdtsc();
  double nsecs = duration_nsec(&t1, &t0);
  printf("clock_gettime says took: %f ns (%f s)\n",nsecs, nsecs / 1e9);
  printf("rdtsc read:              %llu cycles\n",stop-start);
  double duration =  (stop-start) / GetNominalCPUFrequency();
  printf("rdtsc says took:         %f s at %f MHz\n", duration, GetNominalCPUFrequency());
}
```
