### ISSUE TITLE
TIME_DIFFERENCE macro got ‘struct timeval’ has no member named ‘tv_nsec’; did you mean ‘tv_sec’ error

### ISSUE THREAD

**Issue by larrylikestocode** [UBC-ECE-Sasha/PIM-common#5]
https://github.com/UBC-ECE-Sasha/PIM-common/blob/master/host/include/host.h#L9

**Comment by johnramsden** [comment]
In #4 we changed the macro to use `clock_gettime`, the old macro still exists as:

https://github.com/UBC-ECE-Sasha/PIM-common/blob/cac6ca79b2321d386f5e41ce7858c3b8e8cb7b2a/host/include/host.h#L17-L19

**Comment by jnider** [comment]
Are you using clock_gettime() or gettimeofday()? There are different macros for the different structures used by each function.

-------- Original message --------From: Larry Liu <notifications@github.com> Date: 2020-08-04  16:59  (GMT-08:00) To: UBC-ECE-Sasha/PIM-common <PIM-common@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: [UBC-ECE-Sasha/PIM-common] TIME_DIFFERENCE macro got ‘struct timeval’ has no member named ‘tv_nsec’; did you mean ‘tv_sec’ error (#5) 
https://github.com/UBC-ECE-Sasha/PIM-common/blob/master/host/include/host.h#L9

**Comment by larrylikestocode** [comment]
@jnider Are we gonna switchfrom gettimeofday() to clock_gettime() now?

**Comment by jnider** [comment]
clock_gettime() is preferred, but you can choose (they behave the same 
for our purposes). If it is too much work to switch, then stick with 
what you have.

**Comment by larrylikestocode** [comment]
ok Thanks. Cuz the original Sparser code used gettimeofday(), so I will stick to that
